language: ruby
script: bundle exec rake
before_install:
 - sudo apt-get update
 - sudo apt-get install graphicsmagick imagemagick
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
